dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- docker
env:
- TEST_HOST=TRAVIS
before_install:
- sudo /etc/init.d/mysql stop
- make prepare_test_env
install:
- pip install poetry
- poetry config virtualenvs.create false --local
- poetry update
script:
- make test
- make integration_test
after_success:
- make destroy_test_env
- codecov
